services:
  runner:
    build: . 
    container_name: github-runner
    environment:
      REPO_URL: ${REPO_URL}
      GH_PAT: ${GH_PAT} 
      RUNNER_NAME: vps-secure-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
